export const driverRecords = [
  {
    id: 'DRV-102',
    name: 'Ava Carter',
    license: 'LIC-7721',
    route: 'North Loop',
    status: 'Cleared',
    risk: 'Low',
    phone: '+1 (555) 014-2211',
    shift: '06:00 - 14:00',
    lastCheck: 'Today, 07:10',
    violations: 0,
    score: 98,
  },
  {
    id: 'DRV-118',
    name: 'Marcus Lee',
    license: 'LIC-8842',
    route: 'West Corridor',
    status: 'Review',
    risk: 'Medium',
    phone: '+1 (555) 014-3320',
    shift: '14:00 - 22:00',
    lastCheck: 'Today, 10:40',
    violations: 1,
    score: 86,
  },
  {
    id: 'DRV-135',
    name: 'Nina Patel',
    license: 'LIC-9405',
    route: 'South Shuttle',
    status: 'Cleared',
    risk: 'Low',
    phone: '+1 (555) 014-4410',
    shift: '10:00 - 18:00',
    lastCheck: 'Yesterday, 17:20',
    violations: 0,
    score: 95,
  },
  {
    id: 'DRV-146',
    name: 'Jordan Km',
    license: 'LIC-2519',
    route: 'Central Freight',
    status: 'Standby',
    risk: 'High',
    phone: '+1 (555) 014-5578',
    shift: '22:00 - 06:00',
    lastCheck: 'Today, 05:55',
    violations: 2,
    score: 74,
  },
];

export const tripRecords = [
  {
    id: 'TRP-401',
    title: 'North Loop Morning Dispatch',
    driver: 'Ava Carter',
    vehicle: 'GJ-01-AB-1234',
    route: 'Depot to North Hub',
    status: 'On Trip',
    hazard: 'Low',
    start: '06:15',
    eta: '08:40',
    distance: '86 km',
  },
  {
    id: 'TRP-414',
    title: 'West Corridor Inspection Run',
    driver: 'Marcus Lee',
    vehicle: 'GJ-05-KL-3210',
    route: 'West Gate to Industrial Park',
    status: 'Delayed',
    hazard: 'Medium',
    start: '09:10',
    eta: '12:05',
    distance: '54 km',
  },
  {
    id: 'TRP-429',
    title: 'South Shuttle Safety Shift',
    driver: 'Nina Patel',
    vehicle: 'GJ-12-PQ-4567',
    route: 'South Terminal to Airport',
    status: 'Completed',
    hazard: 'Low',
    start: '10:30',
    eta: '13:00',
    distance: '41 km',
  },
];

export const maintenanceRecords = [
  {
    id: 'MT-201',
    title: 'Brake Inspection - GJ-01-AB-1234',
    vehicle: 'GJ-01-AB-1234',
    type: 'Safety Check',
    status: 'Open',
    priority: 'High',
    owner: 'Workshop Alpha',
    due: 'Today',
    findings: 'Front pads wearing unevenly',
  },
  {
    id: 'MT-214',
    title: 'Cab Sensor Calibration - GJ-05-KL-3210',
    vehicle: 'GJ-05-KL-3210',
    type: 'Calibration',
    status: 'In Progress',
    priority: 'Medium',
    owner: 'Workshop Beta',
    due: 'Tomorrow',
    findings: 'Temperature alerts need recalibration',
  },
  {
    id: 'MT-227',
    title: 'Tyre Replacement - GJ-06-MN-8765',
    vehicle: 'GJ-06-MN-8765',
    type: 'Preventive',
    status: 'Closed',
    priority: 'Low',
    owner: 'Workshop West',
    due: 'Completed',
    findings: 'All tyres replaced and verified',
  },
];

export const analyticsSummary = [
  { label: 'Safety cleared drivers', value: '24', note: '92% of active pool' },
  { label: 'Open trip alerts', value: '3', note: 'All acknowledged' },
  { label: 'Critical maintenance jobs', value: '1', note: 'Needs escalation' },
  { label: 'Policy compliance', value: '98.1%', note: 'Month to date' },
];

export const getDriverById = (driverId) => driverRecords.find((driver) => driver.id === driverId) || driverRecords[0];
export const getTripById = (tripId) => tripRecords.find((trip) => trip.id === tripId) || tripRecords[0];
export const getMaintenanceById = (maintenanceId) => maintenanceRecords.find((record) => record.id === maintenanceId) || maintenanceRecords[0];