import { useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowDownRight, ArrowUpRight, BarChart3, CarFront, Download, Droplets, FilterX, Gauge, Landmark, ReceiptText, Settings2, TrendingUp, Wrench } from 'lucide-react';

const money = (value) => `$${value.toLocaleString()}`;
const Card = ({ title, children, action }) => <section className="rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 p-5 shadow-sm"><div className="mb-4 flex items-start justify-between"><div><h2 className="text-sm font-bold text-slate-800 dark:text-white">{title}</h2></div>{action}</div>{children}</section>;
const iconMap = { Revenue: Landmark, Cost: ReceiptText, Fuel: Droplets, Tools: Wrench, Profit: TrendingUp, ROI: BarChart3, Utilization: CarFront, Efficiency: Gauge };
const colors = ['#F59E0B', '#FB923C', '#F97316', '#FDBA74', '#64748B', '#CBD5E1'];

export const FinancialKPICards = ({ items }) => <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{items.map((item) => { const Icon = iconMap[item.icon]; const positive = !item.change.startsWith('-'); return <Card key={item.label} title=""><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400 dark:text-slate-500">{item.label}</p><p className="mt-2 text-2xl font-bold tracking-tight text-slate-800 dark:text-white">{item.value}</p><div className={`mt-2 flex items-center gap-1 text-xs font-semibold ${positive ? 'text-emerald-600' : 'text-rose-600'}`}>{positive ? <ArrowUpRight className="h-3.5 w-3.5" /> : <ArrowDownRight className="h-3.5 w-3.5" />}{item.change}<span className="font-medium text-slate-400 dark:text-slate-500">{item.trend}</span></div></div><span className="rounded-lg bg-amber-50 p-2.5 text-amber-600"><Icon className="h-5 w-5" /></span></div></Card>; })}</div>;

export const FinancialFilters = () => { const [filters, setFilters] = useState({ range: 'This quarter', vehicle: 'All vehicles', type: 'All types', expense: 'All expenses', region: 'All regions' }); const change = (key, value) => setFilters({ ...filters, [key]: value }); const options = { range: ['This month', 'This quarter', 'This year'], vehicle: ['All vehicles', 'TX-9081', 'TX-4322', 'NY-7811', 'CA-8899'], type: ['All types', 'Heavy Duty', 'Van', 'Sedan'], expense: ['All expenses', 'Fuel', 'Maintenance', 'Insurance', 'Repairs'], region: ['All regions', 'North', 'South', 'East', 'West'] }; return <Card title="Financial filters" action={<button onClick={() => setFilters({ range: 'This quarter', vehicle: 'All vehicles', type: 'All types', expense: 'All expenses', region: 'All regions' })} className="inline-flex items-center gap-1 text-xs font-semibold text-slate-500 dark:text-slate-400 dark:text-slate-500 hover:text-amber-600"><FilterX className="h-3.5 w-3.5" />Reset filters</button>}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(options).map(([key, values]) => <label key={key} className="text-xs font-semibold capitalize text-slate-500 dark:text-slate-400 dark:text-slate-500">{key === 'range' ? 'Date range' : key === 'type' ? 'Vehicle type' : key === 'expense' ? 'Expense type' : key}<select value={filters[key]} onChange={(event) => change(key, event.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900 px-3 py-2.5 text-sm font-medium text-slate-700 dark:text-slate-200 outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-100">{values.map((value) => <option key={value}>{value}</option>)}</select></label>)}</div></Card>; };

export const RevenueLineChart = ({ data }) => <Card title="Revenue vs Expenses" action={<span className="text-xs font-medium text-slate-400 dark:text-slate-500">Monthly performance</span>}><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ left: 4, right: 10, top: 8 }}><CartesianGrid stroke="#E2E8F0" vertical={false} /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#64748B', fontSize: 12 }} /><YAxis tickFormatter={(value) => `$${value / 1000}k`} axisLine={false} tickLine={false} tick={{ fill: '#64748B', fontSize: 12 }} /><Tooltip formatter={(value) => money(value)} /><Legend /><Line type="monotone" dataKey="revenue" name="Revenue" stroke="#F59E0B" strokeWidth={3} dot={false} /><Line type="monotone" dataKey="expenses" name="Expenses" stroke="#64748B" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer></div></Card>;

export const ExpensePieChart = ({ data }) => <Card title="Expense Breakdown" action={<span className="text-xs font-medium text-slate-400 dark:text-slate-500">This quarter</span>}><div className="h-72"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={56} outerRadius={90} paddingAngle={3}>{data.map((item, index) => <Cell key={item.name} fill={colors[index]} />)}</Pie><Tooltip formatter={(value) => money(value)} /><Legend /></PieChart></ResponsiveContainer></div></Card>;

export const FuelAnalyticsTable = ({ data }) => <Card title="Fuel Analytics" action={<span className="text-xs text-slate-400 dark:text-slate-500">Poor efficiency flagged</span>}><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-slate-100 dark:border-slate-800 text-[10px] uppercase tracking-widest text-slate-400 dark:text-slate-500"><tr>{['Vehicle', 'Distance', 'Fuel Used', 'Efficiency', 'Fuel Cost', 'Cost / KM'].map((head) => <th key={head} className="px-3 py-3 first:pl-0">{head}</th>)}</tr></thead><tbody>{data.map((row) => <tr key={row.vehicle} className="border-b border-slate-100 dark:border-slate-800 last:border-0"><td className="py-4 pr-3 font-semibold text-slate-700 dark:text-slate-200">{row.vehicle}</td><td>{row.distance}</td><td>{row.fuel}</td><td className={row.poor ? 'font-bold text-rose-600' : 'font-semibold text-emerald-600'}>{row.efficiency}{row.poor && <span className="ml-2 rounded-full bg-rose-50 px-2 py-0.5 text-[10px] uppercase">Review</span>}</td><td>{row.fuelCost}</td><td className="font-semibold text-slate-700 dark:text-slate-200">{row.perKm}</td></tr>)}</tbody></table></div></Card>;

export const VehicleProfitabilityTable = ({ data }) => { const rows = [...data].sort((a, b) => b.roi - a.roi); return <Card title="Vehicle Profitability" action={<span className="text-xs text-slate-400 dark:text-slate-500">Sorted by ROI</span>}><div className="overflow-x-auto"><table className="w-full min-w-[840px] text-left text-sm"><thead className="border-b border-slate-100 dark:border-slate-800 text-[10px] uppercase tracking-widest text-slate-400 dark:text-slate-500"><tr>{['Vehicle', 'Revenue', 'Fuel Cost', 'Maintenance', 'Operational Cost', 'Net Profit', 'ROI'].map((head) => <th key={head} className="px-3 py-3 first:pl-0">{head}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.vehicle} className="border-b border-slate-100 dark:border-slate-800 last:border-0"><td className="py-4 pr-3 font-semibold text-slate-700 dark:text-slate-200">{row.vehicle}</td><td>{money(row.revenue)}</td><td>{money(row.fuel)}</td><td>{money(row.maintenance)}</td><td>{money(row.cost)}</td><td className="font-bold text-emerald-600">{money(row.profit)}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${row.roi >= 20 ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{row.roi}%</span></td></tr>)}</tbody></table></div></Card>; };

export const CostliestVehiclesChart = ({ data }) => <Card title="Top Costliest Vehicles" action={<span className="text-xs text-slate-400 dark:text-slate-500">Operational cost</span>}><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{ left: 18, right: 18 }}><CartesianGrid stroke="#E2E8F0" horizontal={false} /><XAxis type="number" tickFormatter={(value) => `$${value / 1000}k`} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="vehicle" axisLine={false} tickLine={false} /><Tooltip formatter={(value) => money(value)} /><Bar dataKey="cost" name="Operational cost" fill="#F59E0B" radius={[0, 6, 6, 0]} /></BarChart></ResponsiveContainer></div></Card>;

export const RecentExpensesTable = ({ data }) => { const [query, setQuery] = useState(''); const [sortAsc, setSortAsc] = useState(false); const [page, setPage] = useState(0); const rows = useMemo(() => data.filter((item) => `${item.vehicle} ${item.type} ${item.id}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sortAsc ? a.amount - b.amount : b.amount - a.amount), [data, query, sortAsc]); const pageRows = rows.slice(page * 4, page * 4 + 4); return <Card title="Recent Expenses" action={<input value={query} onChange={(event) => { setQuery(event.target.value); setPage(0); }} placeholder="Search expenses…" className="rounded-lg border border-slate-200 dark:border-slate-700 px-3 py-2 text-xs outline-none focus:border-amber-500" />}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-slate-100 dark:border-slate-800 text-[10px] uppercase tracking-widest text-slate-400 dark:text-slate-500"><tr>{['Vehicle', 'Expense Type', 'Amount', 'Date', 'Status'].map((head) => <th key={head} className="px-3 py-3 first:pl-0">{head === 'Amount' ? <button onClick={() => setSortAsc(!sortAsc)} className="font-bold">Amount ↕</button> : head}</th>)}</tr></thead><tbody>{pageRows.map((row) => <tr key={row.id} className="border-b border-slate-100 dark:border-slate-800 last:border-0"><td className="py-4 font-semibold text-slate-700 dark:text-slate-200">{row.vehicle}<span className="ml-2 text-xs font-normal text-slate-400 dark:text-slate-500">{row.id}</span></td><td>{row.type}</td><td className="font-semibold">{money(row.amount)}</td><td>{row.date}</td><td><span className={`rounded-full px-2 py-1 text-xs font-semibold ${row.status === 'Approved' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{row.status}</span></td></tr>)}</tbody></table></div><div className="mt-4 flex items-center justify-between text-xs text-slate-500 dark:text-slate-400 dark:text-slate-500"><span>Showing {pageRows.length} of {rows.length} expenses</span><div className="flex gap-2"><button disabled={page === 0} onClick={() => setPage(page - 1)} className="rounded border border-slate-200 dark:border-slate-700 px-2 py-1 disabled:opacity-40">Previous</button><button disabled={(page + 1) * 4 >= rows.length} onClick={() => setPage(page + 1)} className="rounded border border-slate-200 dark:border-slate-700 px-2 py-1 disabled:opacity-40">Next</button></div></div></Card>; };

export const QuickInsights = ({ items }) => <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map((item) => <Card key={item.label} title=""><p className="text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400 dark:text-slate-500">{item.label}</p><p className="mt-2 text-lg font-bold text-slate-800 dark:text-white">{item.value}</p><p className="mt-1 text-xs text-slate-400 dark:text-slate-500">{item.detail}</p></Card>)}</div>;

export const ExportActions = ({ expenseRows }) => { const exportCsv = () => { const csv = ['Vehicle,Expense Type,Amount,Date,Status', ...expenseRows.map((row) => `${row.vehicle},${row.type},${row.amount},${row.date},${row.status}`)].join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = 'transitops-financial-expenses.csv'; link.click(); URL.revokeObjectURL(url); }; return <div className="flex flex-wrap gap-3"><button onClick={exportCsv} className="inline-flex items-center gap-2 rounded-xl bg-amber-500 px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-orange-600"><Download className="h-4 w-4" />Export CSV</button><button disabled className="inline-flex items-center gap-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 px-4 py-2.5 text-sm font-bold text-slate-400 dark:text-slate-500"><Download className="h-4 w-4" />Export PDF <span className="rounded-full bg-slate-100 dark:bg-slate-800 px-2 py-0.5 text-[10px]">Coming Soon</span></button></div>; };
